### ISSUE TITLE
Newest version crashing nodebb 0.9.3 when marking post as answered

### ISSUE THREAD

**Issue by whittssg** [NodeBB/nodebb-plugin-question-and-answer#28]
I just upgraded to the latest version and when marking a topic as answered, nodebb crashes with the following error:

17/3 11:43 [18316] - error: TypeError: topics.deleteTopicField is not a function
    at C:\Apps\nodebb\node_modules\nodebb-plugin-question-and-answer\library.js:202:13
    at C:\Apps\nodebb\node_modules\async\lib\async.js:718:13
    at async.forEachOf.async.eachOf (C:\Apps\nodebb\node_modules\async\lib\async.js:233:13)
    at _parallel (C:\Apps\nodebb\node_modules\async\lib\async.js:717:9)
    at Object.async.parallel (C:\Apps\nodebb\node_modules\async\lib\async.js:731:9)
    at C:\Apps\nodebb\node_modules\nodebb-plugin-question-and-answer\library.js:194:9
    at C:\Apps\nodebb\src\database\mongo\hash.js:71:4
    at handleCallback (C:\Apps\nodebb\node_modules\mongodb\lib\utils.js:96:12)
    at C:\Apps\nodebb\node_modules\mongodb\lib\collection.js:1335:5
    at handleCallback (C:\Apps\nodebb\node_modules\mongodb\lib\utils.js:96:12)
TypeError: topics.deleteTopicField is not a function
    at C:\Apps\nodebb\node_modules\nodebb-plugin-question-and-answer\library.js:202:13
    at C:\Apps\nodebb\node_modules\async\lib\async.js:718:13
    at async.forEachOf.async.eachOf (C:\Apps\nodebb\node_modules\async\lib\async.js:233:13)
    at _parallel (C:\Apps\nodebb\node_modules\async\lib\async.js:717:9)
    at Object.async.parallel (C:\Apps\nodebb\node_modules\async\lib\async.js:731:9)
    at C:\Apps\nodebb\node_modules\nodebb-plugin-question-and-answer\library.js:194:9
    at C:\Apps\nodebb\src\database\mongo\hash.js:71:4
    at handleCallback (C:\Apps\nodebb\node_modules\mongodb\lib\utils.js:96:12)
    at C:\Apps\nodebb\node_modules\mongodb\lib\collection.js:1335:5
    at handleCallback (C:\Apps\nodebb\node_modules\mongodb\lib\utils.js:96:12)

Thanks,

**Comment by pichalite** [comment]
@whittssg newest version doesn't work with NodeBB v0.9.x. You need NodeBB v1.0

**Comment by whittssg** [comment]
:( thanks..
